language: python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - conda env create -f environment.yml
  - source activate PETSc-GMsFEM
  - python setup.py install

script:
  - pytest -v --cov-config=.coveragerc --cov=./PETScGMsFEM

after_success:
  - codecov
