language: python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install setuptools
  - pip install Cython
  - pip install vtk
  - pip install mpi4py
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install petsc petsc4py
  - pip install slepc4py
  - python setup.py install

script:
  - pytest

after_success:
  - codecov
